all: A.fann B.fann C.fann D.fann E.fann H.fann I.fann J.fann K.fann L.fann M.fann N.fann O.fann P.fann Q.fann R.fann S.fann T.fann U.fann form.fann pos.fann stag.fann

A.fann: 
	./scripts/A_train_fann.sh
	./scripts/A_dev_fann.sh

B.fann: 
	./scripts/B_train_fann.sh
	./scripts/B_dev_fann.sh

C.fann:
	./scripts/C_train_fann.sh
	./scripts/C_dev_fann.sh

D.fann:
	./scripts/D_train_fann.sh
	./scripts/D_dev_fann.sh

E.fann:
	./scripts/E_train_fann.sh
	./scripts/E_dev_fann.sh

#F.fann:
	#./scripts/F_train_fann.sh
	#./scripts/F_dev_fann.sh

#G.fann: 
	#./scripts/G_train_fann.sh
	#./scripts/G_dev_fann.sh

H.fann:
	./scripts/H_train_fann.sh
	./scripts/H_dev_fann.sh

I.fann:
	./scripts/I_train_fann.sh
	./scripts/I_dev_fann.sh

J.fann: 
	./scripts/J_train_fann.sh
	./scripts/J_dev_fann.sh

K.fann:
	./scripts/K_train_fann.sh
	./scripts/K_dev_fann.sh

L.fann: 
	./scripts/L_train_fann.sh
	./scripts/L_dev_fann.sh

M.fann:
	./scripts/M_train_fann.sh
	./scripts/M_dev_fann.sh

N.fann: 
	./scripts/N_train_fann.sh
	./scripts/N_dev_fann.sh

O.fann:
	./scripts/O_train_fann.sh
	./scripts/O_dev_fann.sh

P.fann:
	./scripts/P_train_fann.sh
	./scripts/P_dev_fann.sh

Q.fann:
	./scripts/Q_train_fann.sh
	./scripts/Q_dev_fann.sh

R.fann: 
	./scripts/R_train_fann.sh
	./scripts/R_dev_fann.sh

S.fann:
	./scripts/S_train_fann.sh
	./scripts/S_dev_fann.sh

T.fann:
	./scripts/T_train_fann.sh
	./scripts/T_dev_fann.sh

U.fann: 
	./scripts/U_train_fann.sh
	./scripts/U_dev_fann.sh

form.fann:
	./scripts/form_train_fann.sh
	./scripts/form_dev_fann.sh

pos.fann: 
	./scripts/pos_train_fann.sh
	./scripts/pos_dev_fann.sh

stag.fann: 
	./scripts/stag_train_fann.sh
	./scripts/stag_dev_fann.sh

clean:
	rm ./fanns/*.fann
	rm ./alphas/*.alpha
