all: A.fann B.fann C.fann D.fann E.fann H.fann I.fann J.fann K.fann L.fann M.fann N.fann O.fann P.fann Q.fann R.fann S.fann T.fann U.fann form.fann pos.fann stag.fann

1000: A_1000.fann B_1000.fann C_1000.fann D_1000.fann E_1000.fann H_1000.fann I_1000.fann J_1000.fann K_1000.fann L_1000.fann M_1000.fann N_1000.fann O_1000.fann P_1000.fann Q_1000.fann R_1000.fann S_1000.fann T_1000.fann U_1000.fann form_1000.fann pos_1000.fann stag_1000.fann

A.fann: 
	./scripts/A_train_fann.sh
	./scripts/A_dev_fann.sh

B.fann: 
	./scripts/B_train_fann.sh
	./scripts/B_dev_fann.sh

C.fann:
	./scripts/C_train_fann.sh
	./scripts/C_dev_fann.sh

D.fann:
	./scripts/D_train_fann.sh
	./scripts/D_dev_fann.sh

E.fann:
	./scripts/E_train_fann.sh
	./scripts/E_dev_fann.sh

#F.fann:
	#./scripts/F_train_fann.sh
	#./scripts/F_dev_fann.sh

#G.fann: 
	#./scripts/G_train_fann.sh
	#./scripts/G_dev_fann.sh

H.fann:
	./scripts/H_train_fann.sh
	./scripts/H_dev_fann.sh

I.fann:
	./scripts/I_train_fann.sh
	./scripts/I_dev_fann.sh

J.fann: 
	./scripts/J_train_fann.sh
	./scripts/J_dev_fann.sh

K.fann:
	./scripts/K_train_fann.sh
	./scripts/K_dev_fann.sh

L.fann: 
	./scripts/L_train_fann.sh
	./scripts/L_dev_fann.sh

M.fann:
	./scripts/M_train_fann.sh
	./scripts/M_dev_fann.sh

N.fann: 
	./scripts/N_train_fann.sh
	./scripts/N_dev_fann.sh

O.fann:
	./scripts/O_train_fann.sh
	./scripts/O_dev_fann.sh

P.fann:
	./scripts/P_train_fann.sh
	./scripts/P_dev_fann.sh

Q.fann:
	./scripts/Q_train_fann.sh
	./scripts/Q_dev_fann.sh

R.fann: 
	./scripts/R_train_fann.sh
	./scripts/R_dev_fann.sh

S.fann:
	./scripts/S_train_fann.sh
	./scripts/S_dev_fann.sh

T.fann:
	./scripts/T_train_fann.sh
	./scripts/T_dev_fann.sh

U.fann: 
	./scripts/U_train_fann.sh
	./scripts/U_dev_fann.sh

form.fann:
	./scripts/form_train_fann.sh
	./scripts/form_dev_fann.sh

pos.fann: 
	./scripts/pos_train_fann.sh
	./scripts/pos_dev_fann.sh

stag.fann: 
	./scripts/stag_train_fann.sh
	./scripts/stag_dev_fann.sh

A_1000.fann: 
	./scripts_1000/A_train_fann.sh
	./scripts_1000/A_dev_fann.sh

B_1000.fann: 
	./scripts_1000/B_train_fann.sh
	./scripts_1000/B_dev_fann.sh

C_1000.fann:
	./scripts_1000/C_train_fann.sh
	./scripts_1000/C_dev_fann.sh

D_1000.fann:
	./scripts_1000/D_train_fann.sh
	./scripts_1000/D_dev_fann.sh

E_1000.fann:
	./scripts_1000/E_train_fann.sh
	./scripts_1000/E_dev_fann.sh

F_1000.fann:
	./scripts_1000/F_train_fann.sh
	./scripts_1000/F_dev_fann.sh

G_1000.fann: 
	./scripts_1000/G_train_fann.sh
	./scripts_1000/G_dev_fann.sh

H_1000.fann:
	./scripts_1000/H_train_fann.sh
	./scripts_1000/H_dev_fann.sh

I_1000.fann:
	./scripts_1000/I_train_fann.sh
	./scripts_1000/I_dev_fann.sh

J_1000.fann: 
	./scripts_1000/J_train_fann.sh
	./scripts_1000/J_dev_fann.sh

K_1000.fann:
	./scripts_1000/K_train_fann.sh
	./scripts_1000/K_dev_fann.sh

L_1000.fann: 
	./scripts_1000/L_train_fann.sh
	./scripts_1000/L_dev_fann.sh

M_1000.fann:
	./scripts_1000/M_train_fann.sh
	./scripts_1000/M_dev_fann.sh

N_1000.fann: 
	./scripts_1000/N_train_fann.sh
	./scripts_1000/N_dev_fann.sh

O_1000.fann:
	./scripts_1000/O_train_fann.sh
	./scripts_1000/O_dev_fann.sh

P_1000.fann:
	./scripts_1000/P_train_fann.sh
	./scripts_1000/P_dev_fann.sh

Q_1000.fann:
	./scripts_1000/Q_train_fann.sh
	./scripts_1000/Q_dev_fann.sh

R_1000.fann: 
	./scripts_1000/R_train_fann.sh
	./scripts_1000/R_dev_fann.sh

S_1000.fann:
	./scripts_1000/S_train_fann.sh
	./scripts_1000/S_dev_fann.sh

T_1000.fann:
	./scripts_1000/T_train_fann.sh
	./scripts_1000/T_dev_fann.sh

U_1000.fann: 
	./scripts_1000/U_train_fann.sh
	./scripts_1000/U_dev_fann.sh

form_1000.fann:
	./scripts_1000/form_train_fann.sh
	./scripts_1000/form_dev_fann.sh

pos_1000.fann: 
	./scripts_1000/pos_train_fann.sh
	./scripts_1000/pos_dev_fann.sh

stag_1000.fann: 
	./scripts_1000/stag_train_fann.sh
	./scripts_1000/stag_dev_fann.sh

clean:
	rm ./fanns/*.fann
	rm ./alphas/*.alpha
	rm ./fanns_1000/*.fann
